# Generated by Django 5.0.4 on 2024-05-06 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отдела')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, verbose_name='Точка прохода')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата выдачи')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('I', models.CharField(max_length=100, verbose_name='Имя')),
                ('O', models.CharField(max_length=100, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
            ],
        ),
        migrations.CreateModel(
            name='Passing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_time', models.DateTimeField(verbose_name='')),
                ('_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuskaApp.pass')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuskaApp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuskaApp.pass')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuskaApp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propuskaApp.person')),
                ('document', models.CharField(max_length=100, verbose_name='Паспорт')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация')),
            ],
            bases=('propuskaApp.person',),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propuskaApp.person')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuskaApp.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuskaApp.position')),
            ],
            bases=('propuskaApp.person',),
        ),
        migrations.CreateModel(
            name='WorkerPass',
            fields=[
                ('pass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propuskaApp.pass')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuskaApp.worker')),
            ],
            bases=('propuskaApp.pass',),
        ),
        migrations.CreateModel(
            name='TempPass',
            fields=[
                ('pass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propuskaApp.pass')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuskaApp.visitor')),
                ('escort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuskaApp.worker')),
            ],
            bases=('propuskaApp.pass',),
        ),
        migrations.AddField(
            model_name='pass',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuskaApp.worker'),
        ),
    ]
