# Generated by Django 5.0.4 on 2024-05-06 16:36
import time

from django.db import migrations

from propuskaApp.models import *



def populate_locations(apps,schema_editor):
    objs = Location.objects.bulk_create(
        [
            Location(location_name="Вход"),
            Location(location_name="Выход")
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('propuskaApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_locations, migrations.RunPython.noop),


    ]
