# Generated by Django 5.0.4 on 2024-05-06 16:36
import time

from django.db import migrations

from propuskaApp.models import *



def populate_positions(apps, schema_editor):
    objs = Position.objects.bulk_create(
        [
            Position(name="Менеджер по закупкам"),
            Position(name="Менеджер по продажам"),
            Position(name="Финансовый аналитик"),
            Position(name="Координатор логистики"),
            Position(name="Специалист по кадровому делопроизводству"),
            Position(name="Системный администратор"),
            Position(name="Маркетинговый специалист"),
            Position(name="Бухгалтер"),
            Position(name="Ассистент руководителя"),
            Position(name="Специалист по корпоративным коммуникациям"),
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('propuskaApp', '0002_auto_20240506_1936'),
    ]

    operations = [
        migrations.RunPython(populate_positions, migrations.RunPython.noop),


    ]
