# Generated by Django 5.0.4 on 2024-05-06 17:26

from django.db import migrations

from propuskaApp.models import Visitor


def populate_visitors(apps, schema_editor):

            Visitor(F="Иванов", I="Алексей", O="Сергеевич", document="AB1234567", organization="ООО Рога и Копыта").save()
            Visitor(F="Петрова", I="Елена", O="Андреевна", document="CD9876543", organization="ЗАО Солнечный Банк").save()
            Visitor(F="Смирнов", I="Иван", O="Николаевич", document="EF5432178", organization="ГП Фабрика Процессоров").save()
            Visitor(F="Козлова", I="Ольга", O="Ивановна", document="GH7654321", organization="ОАО ЭлектроТехМаш").save()
            Visitor(F="Морозов", I="Дмитрий", O="Владимирович", document="IJ2345678",
                    organization="ООО Ремонтные Работы").save()
            Visitor(F="Васильев", I="Андрей", O="Петрович", document="KL8765432",
                    organization="НИИ Вычислительных Технологий").save()
            Visitor(F="Николаева", I="Мария", O="Александровна", document="MN4321876",
                    organization="ЗАО Мебельный Мир").save()
            Visitor(F="Соколов", I="Артем", O="Сергеевич", document="OP8765432", organization="ООО СтройИнжПроект").save()
            Visitor(F="Кузнецова", I="Наталья", O="Викторовна", document="QR3218765", organization="ГУП Горводоканал").save()
            Visitor(F="Лебедев", I="Игорь", O="Михайлович", document="ST6789123", organization="ОАО АвтоДорСтрой").save()



class Migration(migrations.Migration):

    dependencies = [
        ('propuskaApp', '0005_workers'),
    ]

    operations = [ migrations.RunPython(populate_visitors, migrations.RunPython.noop),
    ]
