# Generated by Django 5.0.4 on 2024-05-06 17:26

from django.db import migrations

from propuskaApp.models import TempPass, Visitor, Worker


def populate_passes(apps, schema_editor):

            TempPass(date_start="2022-05-01", date_end="2022-05-05", issued_by=Worker.objects.get(pk=1),
                 visitor=Visitor.objects.get(pk=2+10), escort=Worker.objects.get(pk=3)).save()
            TempPass(date_start="2022-06-10", date_end="2022-06-15", issued_by=Worker.objects.get(pk=3),
                 visitor=Visitor.objects.get(pk=4+10), escort=Worker.objects.get(pk=5)).save()
            TempPass(date_start="2022-07-20", date_end="2022-07-25", issued_by=Worker.objects.get(pk=5),
                 visitor=Visitor.objects.get(pk=1+10), escort=Worker.objects.get(pk=2)).save()
            TempPass(date_start="2022-08-15", date_end="2022-08-20", issued_by=Worker.objects.get(pk=2),
                 visitor=Visitor.objects.get(pk=2+10), escort=Worker.objects.get(pk=3)).save()
            TempPass(date_start="2022-09-03", date_end="2022-09-08", issued_by=Worker.objects.get(pk=3),
                 visitor=Visitor.objects.get(pk=1+10), escort=Worker.objects.get(pk=4)).save()
            TempPass(date_start="2022-10-12", date_end="2022-10-17", issued_by=Worker.objects.get(pk=4),
                 visitor=Visitor.objects.get(pk=5+10), escort=Worker.objects.get(pk=3)).save()
            TempPass(date_start="2022-11-24", date_end="2022-11-29", issued_by=Worker.objects.get(pk=3),
                 visitor=Visitor.objects.get(pk=3+10), escort=Worker.objects.get(pk=4)).save()
            TempPass(date_start="2022-12-08", date_end="2022-12-13", issued_by=Worker.objects.get(pk=5),
                 visitor=Visitor.objects.get(pk=4+10), escort=Worker.objects.get(pk=1)).save()
            TempPass(date_start="2023-01-16", date_end="2023-01-21", issued_by=Worker.objects.get(pk=4),
                 visitor=Visitor.objects.get(pk=2+10), escort=Worker.objects.get(pk=3)).save()
            TempPass(date_start="2023-02-27", date_end="2023-03-04", issued_by=Worker.objects.get(pk=1),
                 visitor=Visitor.objects.get(pk=3+10), escort=Worker.objects.get(pk=4)).save()


class Migration(migrations.Migration):

    dependencies = [
        ('propuskaApp', '0006_visitors'),
    ]

    operations = [   migrations.RunPython(populate_passes, migrations.RunPython.noop),
    ]
