# Generated by Django 5.0.4 on 2024-05-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propuskaApp', '0007_passes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerPass',
        ),
    ]
