# Generated by Django 5.0.4 on 2024-05-07 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuskaApp', '0008_delete_workerpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPass',
            fields=[
                ('pass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propuskaApp.pass')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuskaApp.worker')),
            ],
            bases=('propuskaApp.pass',),
        ),
    ]
