# Generated by Django 5.0.4 on 2024-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuskaApp', '0010_alter_pass_issued_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='FIO',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
    ]
