# Generated by Django 5.0.4 on 2024-05-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuskaApp', '0011_person_fio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='F',
        ),
        migrations.RemoveField(
            model_name='person',
            name='I',
        ),
        migrations.RemoveField(
            model_name='person',
            name='O',
        ),
        migrations.AlterField(
            model_name='person',
            name='FIO',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
    ]
